### ISSUE TITLE
Close button disappears on refresh of content

### ISSUE THREAD

**Issue by ItsMorePaul** [CodyHouse/cd-giove-changelog#3]
On the following pages, the close button disappears on refresh:
1. About
2. Work
3. Contact

![Work  Portfolio template by CodyHouse](https://user-images.githubusercontent.com/49879648/132906128-5fe1a02a-95f1-417e-b64f-095700ffd1be.jpeg)

**Comment by claudia-romano** [comment]
Hi Paul, when you refresh the browser, what you see is the actual page (e.g., about.html); that's because we update the browser history each time a new link is clicked. For this reason, you do not need a close button (it's removed on purpose) and you can use the homepage logo link to navigate the website.

**Comment by ItsMorePaul** [comment]
I still find this to be strange behavior, but I understand the justification. Closing issue.
